project_id = "oruwtgdjurstvhgqcvbv"

[functions.gohighlevel-crm]
verify_jwt = false

[functions.template-automation]
verify_jwt = false

[functions.ai-code-assistant]
verify_jwt = false

[functions.ai-design-assistant]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-ai-template]
verify_jwt = false

[functions.generate-template]
verify_jwt = false

[functions.generate-template-image]
verify_jwt = false

[functions.generate-page]
verify_jwt = false

[functions.copy-rewrite]
verify_jwt = false

[functions.publish-site]
verify_jwt = false

[functions.web-builder-ai]
verify_jwt = false

[functions.ai-web-assistant]
verify_jwt = false

[functions.workflow-trigger]
verify_jwt = false

[functions.workflow-cron]
verify_jwt = false

[functions.workflow-job-processor]
verify_jwt = false

[functions.form-submit]
verify_jwt = false
